/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ektp;

/**
 *
 * @author eriS
 */
public class wargaGUI extends javax.swing.JFrame {

    /** Creates new form wargaGUI */
    public wargaGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        inNik = new javax.swing.JLabel();
        inNama = new javax.swing.JLabel();
        inTtl = new javax.swing.JLabel();
        inAlamat = new javax.swing.JLabel();
        inRt = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        inRw = new javax.swing.JLabel();
        inKabupaten = new javax.swing.JLabel();
        inKecamatan = new javax.swing.JLabel();
        inNokk = new javax.swing.JLabel();
        inAgama = new javax.swing.JLabel();
        inStatuspernikahan = new javax.swing.JLabel();
        inPekerjaan = new javax.swing.JLabel();
        inKewarganegaraan = new javax.swing.JLabel();
        inMasaberlaku = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        inKodepos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 30)); // NOI18N
        jLabel1.setText("Data Warga");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel2.setText("NIK                                         :");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel3.setText("Nama                                     :");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel4.setText("Tempat Tanggal Lahir           :");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel5.setText("Alamat                                   :");

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel6.setText("RT / RW                                :");

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel7.setText("Kabupaten                             :");

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel8.setText("Kecamatan                           :");

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel9.setText("No. KK                                  :");

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel10.setText("Agama                                  :");

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel11.setText("Status Pernikahan                :");

        jLabel12.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel12.setText("Pekerjaan                             :");

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel13.setText("Kewarganegaraan               :");

        jLabel14.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel14.setText("Masa Berlaku                      :");

        inNik.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        inNik.setText("jLabel15");

        inNama.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        inNama.setText("jLabel16");

        inTtl.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        inTtl.setText("jLabel17");

        inAlamat.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        inAlamat.setText("jLabel18");

        inRt.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        inRt.setText("jLabel19");

        jLabel20.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel20.setText("/");

        inRw.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        inRw.setText("jLabel21");

        inKabupaten.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        inKabupaten.setText("jLabel22");

        inKecamatan.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        inKecamatan.setText("jLabel23");

        inNokk.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        inNokk.setText("jLabel24");

        inAgama.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        inAgama.setText("jLabel25");

        inStatuspernikahan.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        inStatuspernikahan.setText("jLabel26");

        inPekerjaan.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        inPekerjaan.setText("jLabel27");

        inKewarganegaraan.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        inKewarganegaraan.setText("jLabel28");

        inMasaberlaku.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        inMasaberlaku.setText("jLabel29");

        jLabel15.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jLabel15.setText("Kode Pos                              : ");

        inKodepos.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        inKodepos.setText("jLabel16");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(185, 185, 185))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(inNama, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(inNik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(inTtl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(inAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(inRt)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(inRw))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(inKabupaten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(inKecamatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(inNokk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addComponent(inAgama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(inStatuspernikahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(18, 18, 18)
                            .addComponent(inPekerjaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(18, 18, 18)
                            .addComponent(inKewarganegaraan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(18, 18, 18)
                            .addComponent(inMasaberlaku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inKodepos)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(inNik))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(inNama))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(inTtl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(inAlamat))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(inRt)
                            .addComponent(jLabel20)
                            .addComponent(inRw))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(inKabupaten))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addComponent(inKecamatan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(inKodepos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(inNokk))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(inAgama))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(inStatuspernikahan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(inPekerjaan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(inKewarganegaraan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(inMasaberlaku))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wargaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wargaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wargaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wargaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wargaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel inAgama;
    private javax.swing.JLabel inAlamat;
    private javax.swing.JLabel inKabupaten;
    private javax.swing.JLabel inKecamatan;
    private javax.swing.JLabel inKewarganegaraan;
    private javax.swing.JLabel inKodepos;
    private javax.swing.JLabel inMasaberlaku;
    private javax.swing.JLabel inNama;
    private javax.swing.JLabel inNik;
    private javax.swing.JLabel inNokk;
    private javax.swing.JLabel inPekerjaan;
    private javax.swing.JLabel inRt;
    private javax.swing.JLabel inRw;
    private javax.swing.JLabel inStatuspernikahan;
    private javax.swing.JLabel inTtl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
